/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikurir;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakyd
 */
public class FormKurir extends javax.swing.JFrame {
 LogikaKurir kurir = new LogikaKurir();
 
 private double harga_pelindung = 0;
 private String pembayaran;
    /**
     * Creates new form FormKurir
     */
    public FormKurir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        bodypanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        btHome = new javax.swing.JButton();
        btKirim = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        btStatus = new javax.swing.JButton();
        MainPanel1 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        KirimPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbLayanan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cBubble = new javax.swing.JCheckBox();
        cKotakKayu = new javax.swing.JCheckBox();
        cPlastikHitam = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        tfJarak = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfBeratPaket = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfPelindung = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rbLunas = new javax.swing.JRadioButton();
        rbBayarDiTempat = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tfTotalBayar = new javax.swing.JTextField();
        bBuatPesanan = new javax.swing.JButton();
        StatusPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTampil = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI KURIR");

        bodypanel.setBackground(new java.awt.Color(0, 255, 204));

        MenuPanel.setBackground(new java.awt.Color(0, 255, 204));
        MenuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btHome.setText("HOME");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btKirim.setText("KIRIM BARANG");
        btKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKirimActionPerformed(evt);
            }
        });

        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        btStatus.setText("STATUS BARANG");
        btStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btKeluar))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btKirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btHome)
                .addGap(18, 18, 18)
                .addComponent(btKirim)
                .addGap(18, 18, 18)
                .addComponent(btStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btKeluar)
                .addContainerGap())
        );

        MainPanel1.setBackground(new java.awt.Color(0, 255, 204));
        MainPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        MainPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("MENU HOME");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        MainPanel1.add(HomePanel, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("MENU KIRIM BARANG");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Pengisian Data");

        jLabel4.setText("Nama Pengirim / Toko");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat Tujuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNama)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setText("Detail Pengiriman");

        jLabel8.setText("Layanan");

        cbLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "SAME DAY", "INSTANT", "KARGO" }));
        cbLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLayananActionPerformed(evt);
            }
        });

        jLabel9.setText("Pelindung Tambahan");

        cBubble.setText("Bubble Warp");
        cBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBubbleActionPerformed(evt);
            }
        });

        cKotakKayu.setText("Kotak Kayu");
        cKotakKayu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKotakKayuActionPerformed(evt);
            }
        });

        cPlastikHitam.setText("Plastik Hitam");
        cPlastikHitam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPlastikHitamActionPerformed(evt);
            }
        });

        jLabel12.setText("Jarak Tujuan /KM");

        tfJarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJarakActionPerformed(evt);
            }
        });
        tfJarak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfJarakKeyPressed(evt);
            }
        });

        jLabel13.setText("Berat Paket /KG");

        tfBeratPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeratPaketActionPerformed(evt);
            }
        });
        tfBeratPaket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBeratPaketKeyPressed(evt);
            }
        });

        jLabel14.setText("Harga Pelindung Tambahan");

        tfPelindung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPelindungActionPerformed(evt);
            }
        });

        bHitung.setText("HITUNG");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfPelindung, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bHitung))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBeratPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cBubble)
                                        .addGap(18, 18, 18)
                                        .addComponent(cKotakKayu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cPlastikHitam))
                                    .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 70, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(tfJarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(tfBeratPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cBubble)
                    .addComponent(cKotakKayu)
                    .addComponent(cPlastikHitam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfPelindung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHitung))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        jLabel10.setText("Pembayaran");

        bg.add(rbLunas);
        rbLunas.setText("Lunas");
        rbLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunasActionPerformed(evt);
            }
        });

        bg.add(rbBayarDiTempat);
        rbBayarDiTempat.setText("Bayar Di Tempat");
        rbBayarDiTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBayarDiTempatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLunas)
                    .addComponent(rbBayarDiTempat))
                .addGap(0, 181, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbBayarDiTempat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Total Bayar");

        tfTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalBayarActionPerformed(evt);
            }
        });

        bBuatPesanan.setText("BUAT PESANAN");
        bBuatPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuatPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KirimPanelLayout = new javax.swing.GroupLayout(KirimPanel);
        KirimPanel.setLayout(KirimPanelLayout);
        KirimPanelLayout.setHorizontalGroup(
            KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KirimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(KirimPanelLayout.createSequentialGroup()
                        .addGroup(KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bBuatPesanan)
                                .addGroup(KirimPanelLayout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(tfTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        KirimPanelLayout.setVerticalGroup(
            KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KirimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KirimPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(bBuatPesanan))
                    .addGroup(KirimPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        MainPanel1.add(KirimPanel, "card3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("STATUS BARANG");

        tbTampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "ALAMAT TUJUAN", "STATUS PEMBAYARAN"
            }
        ));
        jScrollPane1.setViewportView(tbTampil);

        jButton3.setText("SELESAI");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        MainPanel1.add(StatusPanel, "card4");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        
        // REMOVE PANEL
        MainPanel1.removeAll();
        MainPanel1.repaint();
        MainPanel1.revalidate();
        
        // add panel
        MainPanel1.add(HomePanel);
        MainPanel1.repaint();
        MainPanel1.revalidate();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKirimActionPerformed
        // TODO add your handling code here:
        
         
        // REMOVE PANEL
        MainPanel1.removeAll();
        MainPanel1.repaint();
        MainPanel1.revalidate();
        
        // add panel
        MainPanel1.add(KirimPanel);
        MainPanel1.repaint();
        MainPanel1.revalidate();
    }//GEN-LAST:event_btKirimActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
          int x ;
        x = JOptionPane.showConfirmDialog(null, "Yakin mau keluar??", "Konfirm", 
                JOptionPane.YES_NO_OPTION);
        if (x==JOptionPane.YES_NO_OPTION){
            dispose();
        }else{
            return;}
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStatusActionPerformed
        // TODO add your handling code here:
        
         MainPanel1.removeAll();
        MainPanel1.repaint();
        MainPanel1.revalidate();
        
        // add panel
        MainPanel1.add(StatusPanel);
        MainPanel1.repaint();
        MainPanel1.revalidate();
    }//GEN-LAST:event_btStatusActionPerformed

    private void cBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBubbleActionPerformed
        // TODO add your handling code here:
    
        if (cBubble.isSelected()){
            harga_pelindung += 5_000;
        } else {
            harga_pelindung -= 5_000;
        }
        
        kurir.setHarga_Pelindung_Tambahan(harga_pelindung);
        tfPelindung.setText(Double.toString(harga_pelindung));
        
    }//GEN-LAST:event_cBubbleActionPerformed

    private void tfTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalBayarActionPerformed

    private void bBuatPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuatPesananActionPerformed
        // TODO add your handling code here:
        String nama = tfNama.getText();
        String alamat = tfAlamat.getText();
        DefaultTableModel model = (DefaultTableModel) tbTampil.getModel();
        Object [] rowdata = {nama,alamat,pembayaran};
        model.addRow(rowdata);
     
        
        
    }//GEN-LAST:event_bBuatPesananActionPerformed

    private void cbLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLayananActionPerformed
        // TODO add your handling code here:
        kurir.setJenis_layanan(cbLayanan.getSelectedItem().toString());
        tfTotalBayar.setText(Double.toString(kurir.getHarga_Layanan()));
    }//GEN-LAST:event_cbLayananActionPerformed

    private void tfBeratPaketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeratPaketKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == KeyEvent.VK_ENTER){
          kurir.setBerat_Paket(Double.parseDouble(tfBeratPaket.getText()));
          kurir.setHarga_Jarak();
          kurir.setHarga_Berat_Paket();
          kurir.setHitung_Harga_Berat();
          tfTotalBayar.setText(Double.toString(kurir.getTotal_bayar_Berat()));
          }
    }//GEN-LAST:event_tfBeratPaketKeyPressed

    private void tfJarakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJarakKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         kurir.setJarak(Double.parseDouble(tfJarak.getText()));
         kurir.setHarga_Jarak();
         tfTotalBayar.setText(Double.toString(kurir.getTotal_bayar()));
         }
    }//GEN-LAST:event_tfJarakKeyPressed

    private void tfPelindungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPelindungActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfPelindungActionPerformed

    private void cKotakKayuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKotakKayuActionPerformed
        // TODO add your handling code here:
//          double harga_pelindung = 0;
        if (cKotakKayu.isSelected()){
            harga_pelindung += 20_000;
        } else {
            harga_pelindung -= 20_000;
        }
        
        kurir.setHarga_Pelindung_Tambahan(harga_pelindung);
        tfPelindung.setText(Double.toString(harga_pelindung));
    }//GEN-LAST:event_cKotakKayuActionPerformed

    private void cPlastikHitamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPlastikHitamActionPerformed
        // TODO add your handling code here:
//          double harga_pelindung = 0;
        if (cPlastikHitam.isSelected()){
            harga_pelindung += 2_000;
        } else {
            harga_pelindung -= 2_000;
        }
        
        kurir.setHarga_Pelindung_Tambahan(harga_pelindung);
        tfPelindung.setText(Double.toString(harga_pelindung));
    }//GEN-LAST:event_cPlastikHitamActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        kurir.setTotal_Harga_pelindung_Tambahan(harga_pelindung);
        kurir.setTotal_Bayar_Semua();
        tfTotalBayar.setText(Double.toString(kurir.getTotal_bayar()));
        
    }//GEN-LAST:event_bHitungActionPerformed

    private void tfBeratPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeratPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBeratPaketActionPerformed

    private void tfJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJarakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJarakActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void rbLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunasActionPerformed
        // TODO add your handling code here:
        if (rbLunas.isSelected()){
            pembayaran = "LUNAS";
        }
        
    }//GEN-LAST:event_rbLunasActionPerformed

    private void rbBayarDiTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBayarDiTempatActionPerformed
        // TODO add your handling code here:
        if (rbBayarDiTempat.isSelected()){
            pembayaran = "BAYAR DI TEMPAT";
        }
    }//GEN-LAST:event_rbBayarDiTempatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel KirimPanel;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JButton bBuatPesanan;
    private javax.swing.JButton bHitung;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btKirim;
    private javax.swing.JButton btStatus;
    private javax.swing.JCheckBox cBubble;
    private javax.swing.JCheckBox cKotakKayu;
    private javax.swing.JCheckBox cPlastikHitam;
    private javax.swing.JComboBox<String> cbLayanan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBayarDiTempat;
    private javax.swing.JRadioButton rbLunas;
    private javax.swing.JTable tbTampil;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfBeratPaket;
    private javax.swing.JTextField tfJarak;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfPelindung;
    private javax.swing.JTextField tfTotalBayar;
    // End of variables declaration//GEN-END:variables
}
